### ISSUE TITLE
DID Provider

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#4]
```
cip: 25
title: DID Provider
author: Paul LeCam (@PaulLeCam), Joel Thorstensson (@oed)
status: Idea
category: Standards
type: Interface
created: 2020-05-22
requires:
```

> 🚨 This is a placeholder for an idea, and we will work to draft the CIP at a later time. Feel free to leave comments and ideas on this issue.

## Simple Summary

**DID Provider** describes a standard JSON RPC interface for interacting with DIDs.

**Comment by michaelsena** [comment]
@oed @PaulLeCam it would be great if we could write this CIP to describe the didProvider interface

**Comment by PaulLeCam** [comment]
## Abstract

TODO

## Motivation

TODO

## Specification

DID providers must support receiving request and sending responses according to the [JSON-RPC 2.0 specification](https://www.jsonrpc.org/specification) and create [JSON Web Signatures (JWS)](https://tools.ietf.org/html/rfc7515).

The following JSON-RPC methods must be implemented:

### did_authenticate

**Parameters:** none.

**Expected behavior:** the provider returns the string representation of the DID associated to the user. If no DID exists, a new one is created.

**Expected result:** a JSON object containing the authenticated user’s `"did": string`.

**Possible errors:** TBD

**UX considerations:** the provider might interactively request the user consent before granting this authentication request.

### did_createJWS

**Parameters:** JSON object with the following fields:
- `payload` (required): JSON object to sign
- `protected` (optional): additional header JSON object
- `pubKeyId` (optional): string identifier of the key to use for signing

**Expected behavior:**
- ensure the session is correctly authenticated and the specified signing key (if `pubKeyId` is provided) can be used
- sort both the `payload` and `protected` (if provided) objects as stable objects (TODO: ref to spec or similar)
- create the JWS string for the given parameters, using the [JWS Compact Serialization format](https://tools.ietf.org/html/rfc7515#section-3.1)

**Expected result:** a JSON object containing the created signature as `"jws": string`.

**Possible errors:** TBD

## Rationale

TODO

## Implementation

A JavaScript implementation of the DID Provider is implemented in [3Box’ Identity Wallet](https://github.com/3box/identity-wallet-js).

## Security Considerations

TODO

**Comment by PaulLeCam** [comment]
@oed I used the error codes from https://eips.ethereum.org/EIPS/eip-1193 as I think they're a good match here, any preference or other reference I should use instead please?

**Comment by oed** [comment]
@PaulLeCam Thats a great addition. Can you suggest that in the EIP I created?

**Comment by PaulLeCam** [comment]
Sure, I think most of the contents of this CIP should refer to your EIP anyways so better specify as much as possible in it 👍

**Comment by oed** [comment]
Replaced by: https://eips.ethereum.org/EIPS/eip-2844, closing.
